-- GAUtil.lua

-- I'm not sure how to use the 'module' function, so
-- I'm going to create this module using the old-school method.
local GAUtil = {}

------------------------------------------------------------------------
-- Configure a GA generated by a 3-dimensional Euclidean vector space.
------------------------------------------------------------------------
function GAUtil.EGA3D( galua_api )
	local basisVecs = { "e1", "e2", "e3" }
	galua_api.def_basis( basisVecs )
	local basisVecIPFunc = function( i, j )
		local ip_table =
		{
			{ 1, 0, 0 },
			{ 0, 1, 0 },
			{ 0, 0, 1 },
		}
		return ip_table[i][j]
	end
	galua_api.def_sig( basisVecIPFunc )
end

------------------------------------------------------------------------
-- Configure a Minkowski GA generated by a 5-dimensional vector space.
------------------------------------------------------------------------
function GAUtil.CGA3D( galua_api )
local basisVecs = { "no", "ni", "e1", "e2", "e3" }
	galua_api.def_basis( basisVecs )
	local basisVecIPFunc = function( i, j )
		local ip_table =
		{
			{  0, -1,  0,  0,  0 },
			{ -1,  0,  0,  0,  0 },
			{  0,  0,  1,  0,  0 },
			{  0,  0,  0,  1,  0 },
			{  0,  0,  0,  0,  1 },
		}
		return ip_table[i][j]
	end
	galua_api.def_sig( basisVecIPFunc )
end

------------------------------------------------------------------------
-- Configure a Minkowski mother algebra generated by a
-- 10-dimensional vector space.
------------------------------------------------------------------------
function GAUtil.QGA3D( galua_api )
	local basisVecs =
	{
		"no", "ni", "e1", "e2", "e3",
		"nob", "nib", "e1b", "e2b", "e3b"
	}
	galua_api.def_basis( basisVecs )
	local basisVecIPFunc = function( i, j )
		local ip_table =
		{
			{  0, -1,  0,  0,  0 },
			{ -1,  0,  0,  0,  0 },
			{  0,  0,  1,  0,  0 },
			{  0,  0,  0,  1,  0 },
			{  0,  0,  0,  0,  1 },
		}
		if i <= 5 and j <= 5 then
			return ip_table[i][j]
		elseif i > 5 and j > 5 then
			return ip_table[ i - 5 ][ j - 5 ]
		end
		return 0
	end
	galua_api.def_sig( basisVecIPFunc )
	local basisVecBarFunc = function( i )
		if i <= 5 then
			return i + 5, 1
		end
		return i - 5, -1
	end
	galua_api.def_bar( basisVecBarFunc )
end

-- Return the API table for this module.
return GAUtil

-- GAUtil.lua