-- Return a function that configures a Minkowski geometric
-- algebra generated by a 5-dimensional vector space.
return function( galua_api )
	local basisVecs = { "no", "ni", "e1", "e2", "e3" }
	galua_api.def_basis( basisVecs )
	local basisVecIPFunc = function( i, j )
		local ip_table =
		{
			{  0, -1,  0,  0,  0 },
			{ -1,  0,  0,  0,  0 },
			{  0,  0, +1,  0,  0 },
			{  0,  0,  0, +1,  0 },
			{  0,  0,  0,  0, +1 },
		}
		return ip_table[i][j]
	end
	galua_api.def_sig( basisVecIPFunc )
end