-- Return a function that configures a geometric algebra
-- generated by a 3-dimensional Euclidean vector space.
return function( galua_api )
	local basisVecs = { "e1", "e2", "e3" }
	galua_api.def_basis( basisVecs )
	local basisVecIPFunc = function( i, j )
		local ip_table =
		{
			{ 1, 0, 0 },
			{ 0, 1, 0 },
			{ 0, 0, 1 },
		}
		return ip_table[i][j]
	end
	galua_api.def_sig( basisVecIPFunc )
end