-- Return a function that configures a Minkowski mother
-- algebra generated by a 10-dimensional vector space.
return function( galua_api )
	local basisVecs =
	{
		"no", "ni", "e1", "e2", "e3",
		"nob", "nib", "e1b", "e2b", "e3b"
	}
	galua_api.def_basis( basisVecs )
	local basisVecIPFunc = function( i, j )
		local ip_table =
		{
			{  0, -1,  0,  0,  0 },
			{ -1,  0,  0,  0,  0 },
			{  0,  0,  1,  0,  0 },
			{  0,  0,  0,  1,  0 },
			{  0,  0,  0,  0,  1 },
		}
		if i <= 5 and j <= 5 then
			return ip_table[i][j]
		elseif i > 5 and j > 5 then
			return ip_table[ i - 5 ][ j - 5 ]
		end
		return 0
	end
	galua_api.def_sig( basisVecIPFunc )
	local basisVecBarFunc = function( i )
		if i <= 5 then
			return i + 5, 1
		end
		return i - 5, -1
	end
	galua_api.def_bar( basisVecBarFunc )
end